version: '3'

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: creditproject
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - creditdb-data:/var/lib/mysql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backendNetwork

  creditapi:
    image: openjdk:8u201-jdk-alpine3.9
    container_name: creditapi
    ports:
    - 8080:8080
    depends_on:
      - database
    volumes:
      - ./SpringBoot Credit/target/springbootcredit-credit.0.0.1.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork

  productapi:
    image: openjdk:8u201-jdk-alpine3.9
    container_name: productapi
    ports:
    - 8081:8081
    depends_on:
      - database
    volumes:
    - ./SpringBoot Product/target/springbootproduct-product.0.0.1.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork


  customerapi:
    image: openjdk:8u201-jdk-alpine3.9
    container_name: customerapi
    ports:
    - 8082:8082
    depends_on:
      - database
    volumes:
    - ./SpringBoot Customer/target/springbootcustomer-customer.0.0.1.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork

volumes:
  creditdb-data:

networks:
  backendNetwork: